name: workflow

env:
  WORKDIR: data/ 
  PREPARE: gridlabd python prepare.py
  SIMULATE: gridlabd -D keep_process=TRUE -T 0 main.glm
  ANALYSE: gridlabd python analyse.py
  RETAIN_DAYS: 90

on:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  run-pipeline:

    runs-on: ubuntu-latest
    container: lfenergy/arras:latest

    steps:

    - uses: actions/checkout@v3

    - name: Check node
      run: |
        if command -v node </dev/null >/dev/null 2>&1
        then
          echo 'node is ok'
        else
          echo 'Installing node...' 
          curl -sS https://webi.sh/node | sh 1>/dev/null 
          echo ~/.local/opt/node/bin >> $GITHUB_PATH    
        fi

    - name: Checkout project
      run: |
        test -d $WORKDIR || ( echo "Missing $WORKDIR folder" ; false )
        test -f $WORKDIR/prepare.py || ( echo "ERROR: missing $WORKDIR/prepare.py" ; false )
        test -f $WORKDIR/main.glm || ( echo "missing $WORKDIR/main.glm" ; false )
        test -f $WORKDIR/analyse.py || ( echo "missing" $WORKDIR/analyse.py ; false )
        echo "Workflow settings:"
        echo "  WORKDIR=$WORKDIR"
        echo "  PREPARE=$PREPARE"
        echo "  SIMULATE=$SIMULATE"
        echo "  ANALYSE=$ANALYSE"

    - name: Prepare data
      run: |
        cd $WORKDIR 
        $PREPARE

    - name: Simulate system
      run: |
        cd $WORKDIR
        $SIMULATE
    
    - name: Analyse results
      run: |
        cd $WORKDIR
        $ANALYSE

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: ${{ env.WORKDIR }}/*
        retain-days: ${{ env.RETAIN_DAYS }}

    - name: Output artifact ID
      run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
